backend:
  name: github
  repo: hnunnery/gridsome-vuetify

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - {
          label: "date",
          name: date",
          widget: "date",
          default: "",
          format: "MMM DD, YYYY",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Preview", name: "preview", widget: "markdown" }
    # fields used in home page
  - name: "home"
    label: "Home"
    folder: "home"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Paragraph1", name: "paraOne", widget: "string" }
      - { label: "Paragraph2", name: "paraTwo", widget: "string" }
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Code", name: "code", widget: "string" }
